version: '3.8'

services:
  # Server Service (Backend)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: cyber_audit_server
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env.development
    networks:
      - app-network

  # Client Service (Frontend)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        # This URL points to the server service within the Docker network
        VITE_API_URL: http://server:5000/api
    container_name: cyber_audit_client
    restart: unless-stopped
    ports:
      - "8080:80" # Access the client via http://localhost:8080
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
